export const FACEBOOK_LOGIN_SUCCESS = 'facebook_login_success'
export const FACEBOOK_LOGIN_FAIL = 'facebook_login_fail'
export const REMOVE_FB_TOKEN = 'remove_fb_token'
export const SET_JWT = 'set_jwt'
export const FETCH_PARTICIPANTS = 'fetch_participants'
